### ISSUE TITLE
[Question] APK or F-Droid ?

### ISSUE THREAD

**Issue by KaKi87** [Sash0k/ActivityLauncher#1]
Hello,

Could you make your fork downloadable directly as APK and/or through an open source store like F-Droid ?

I would like to check that I can reproduce butzist/ActivityLauncher#193 on your fork before reporting it, but I can't do that until it is freely accessible.

Thanks

**Comment by Sash0k** [comment]
Hello, f-droid [in progress ](https://gitlab.com/fdroid/rfp/-/issues/2360)

**Comment by KaKi87** [comment]
Alright, please notify me once published and I'll test right away.

**Comment by Sash0k** [comment]
https://f-droid.org/en/packages/de.szalkowski.activitylauncher.rustore_fork

**Comment by KaKi87** [comment]
Thanks.

Well, I upgraded to Android 13 since then, and now both the original app and your fork work properly at opening Developer Options, so I can't confirm whether you fixed the issue or not :sweat_smile:
